image:
- Visual Studio 2015
- Ubuntu

version: '{build}'

init:
  - ps: |
      $PSVersionTable
      git config --global core.autocrlf false
      git config --list --show-origin

install:
  - ps: |
      Install-Module -Name "Pester" -Scope "CurrentUser" -Force

build_script:
  - ps: |
      $ErrorActionPreference = "Stop"
      .\Build.ps1 -Task "CI"

test_script:
  - ps: |
      $PesterTestResultsFile = ".\TestsResults.xml"
      $Pester = Invoke-Pester -OutputFormat NUnitXml -OutputFile $PesterTestResultsFile -PassThru
      $WebClient = New-Object "System.Net.WebClient"
      $PesterTestResultsFilePath = Resolve-Path -Path $PesterTestResultsFile
      $WebClient.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", $PesterTestResultsFilePath)
      If ($Pester.FailedCount -Gt 0) {
          Throw "$(${Pester}.FailedCount) tests failed."
      }

on_finish:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      $ZipFolder = Join-Path -Path $PWD -ChildPath $env:APPVEYOR_PROJECT_NAME
      $ZipFile = Join-Path -Path $PWD -ChildPath "$($env:APPVEYOR_PROJECT_NAME)_$($env:APPVEYOR_BUILD_VERSION).zip"
      Compress-Archive -Path $ZipFolder -DestinationPath $ZipFile
      Push-AppveyorArtifact -Path $ZipFile
